<?php require_once './templates/header.phtml'?>
<h1>Nuestros clientes son:</h1>
<form class="form-control form-control-sm" method="post" action="addClient">
    <label class="h5">Ingrese nombre</label>
        <input type="text" name="nombre" id="nombre">
    </select>
    <label class="h5">Ingrese apellido</label>
        <input type="text" name="apellido" id="apellido">
    </select>
    <label class="h5">Ingrese una edad</label>
        <input type="number" name="edad" id="edad">
    </select>
    <button type="submit" class='btn btn-success ml-auto'>Agregar</button>
</form>
<table class="table table-dark table-striped table-hover">
    <thead>
        <th>Nombre</th>
        <th>apellido</th>
        <th>edad</th>
        <th></th>
        <th></th>
    </thead>
    <?php
    foreach($list as $item):?>
    
    <tbody>
        <tr>
            <td><?= $item->nombre ?></td>
            <td><?= $item->apellido ?></td>
            <td><?= $item->edad ?></td>
            <td><a href="removeClient/<?= $item->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a></td>
            <td><a href="clientEdit/<?= $item->id ?>" type="button" class='btn btn-success ml-auto'>Editar</a></td>

        </tr>
    </tbody>
    <?php endforeach?> 
</table>  
<?php require_once './templates/footer.phtml'?>