<?php require_once './templates/header.phtml'?>

<h1>Lista de pedidos:</h1>

<form class="form-control form-control-sm" method="post" action="add">
    <label class="h5">Ingrese su producto</label>
    <select name="producto" id="producto">
        
    <?php
    foreach($productList as $item):?>
        <option value="<?= $item->idProducto ?>"><?= $item->producto?></option>
        <?php endforeach?>
    </select>
    <label class="h5">Ingrese cuantas unidades</label>
    <input type="number" name="unidades" id="unidades ">
    </select>
    <label class="h5">Ingrese un cliente</label>
    <select name="cliente" id="cliente" >
    <?php
    foreach($clientList as $item):?>
        <option value="<?= $item->id?>"><?= $item->nombre?> <?= $item->apellido?></option>
        <?php endforeach?>
        </select>   

    <button type="submit" class='btn btn-success  ml-auto'>Agregar</button>    
</form>


<form method="post" action="filtrar"  class="form-control form-control-sm">
<label class="h5">Flitrar por</label>
    <select name="filtroCliente" id="filtroCliente">
    <option ></option>
    <?php
    foreach($clientList as $item):?>
        <option value="<?= $item->id?>"><?= $item->nombre?> <?= $item->apellido?></option>
        <?php endforeach?>

    </select>
    <button type="submit" class='btn btn-success ml-auto'>Filtrar </button>  
</form>  





<table class="table table-dark table-striped table-hover">
    <thead>
        <th>Producto</th>
        <th>unidades</th>
        <th>Precio unitario</th>
        <th>Monto total</th>
        <th>Cliente</th>
        <th></th>
        <th></th>
    </thead>

    <?php
    foreach($list as $item):?>
    
        <tbody>
            <tr>
                <td><a href="product    /<?= $item->idProducto?>"><?=  $item->producto?> </a></td>
                <td><?= $item->unidades ?></td> 
                <td><?= $item->monto?></td> 
                <td><?= $item->montoTotal?></td> 
                <td><a href="client/<?= $item->cliente ?>"><?= $item->nombre?> <?= $item->apellido?></a></td> 
                <td><a href="remove/<?= $item->idVenta ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a></td>
                <td><a href="edit/<?= $item->idVenta ?>" type="button" class='btn btn-success ml-auto'>Editar</a></td>

            </tr>
        </tbody>
    <?php endforeach?>
    

</table>
    
<?php require_once './templates/footer.phtml'?>