<?php require_once './templates/header.phtml'?>
<h1>Lista de items</h1>

<form method="post" action="add">
    <label>Ingrese su producto</label>
    <select name="producto" id="prodcuto">
        <option value="bolsa de cemento">Bolsa de cemento</option>
        <option value="pegamento para porcelanatto">Pegamento para porcelanatto</option>
        <option value="lata de hidrofugo">Lata de hidrofugo</option>
        <option value="bolsa de arena">Bolsa de arena</option>
        <option value="ladrillos">Ladrillos</option>
    </select>
    <label>Ingrese cuantas unidades</label>
    <input type="number" name="unidades" id="unidades ">
    </select>
    <label>Ingrese un cliente</label>
    <select name="cliente" id="cliente">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
    </select>
    <button type="submit">Agregar</button>
</form>
<table class="table table-dark">
    <thead>
        <th>Id</th>
        <th>Producto</th>
        <th>unidades</th>
        <th>Precio unitario</th>
        <th>Monto total</th>
        <th>Cliente</th>
    </thead>

    <?php
    foreach($list as $item):?>
        <tbody>
            <tr>
                <td><?= $item->id ?></td>
                <td><?= $item->producto ?></td>
                <td><?= $item->unidades ?></td> 
                <td><?= $item->	montoUnitario?></td> 
                <td><?= $item->montoTotal?></td> 
                <td><a href="client/"><?= $item->cliente ?></a></td> 
                <td><a href="remove/<?= $item->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a></td>
            </tr>
        </tbody>
    <?php endforeach?>
    

</table>
    
<?php require_once './templates/footer.phtml'?>