<?php require_once './templates/header.phtml'?>
<h1>Lista de pedidos</h1>
<table class="table table-dark">
    <thead>
        <th>Id</th>
        <th>Producto</th>
        <th>unidades</th>
        <th>Cliente</th>
    </thead>

    <?php
    foreach($list as $item):?>
        <tbody>
            <tr>
                <td><?= $item->id ?></td>
                <td><?= $item->producto ?></td>
                <td><?= $item->unidades ?></td> 
                <td><a href="client/"><?= $item->cliente ?></a></td> 
            </tr>
        </tbody>
    <?php endforeach?>
    

</table>
    
<?php require_once './templates/footer.phtml'?>