<?php require_once './templates/header.phtml'?>
<h1>Nuestros productos son:</h1>

<table class="table table-dark table-striped table-hover">
    <thead>
        <th>Producto</th>
        <th>Precio</th>
        <th>Descripcion</th>
    </thead>
    <?php
    foreach($list as $item):?>
    
    <tbody>
        <tr>
            <td><?= $item->producto ?></td>
            <td><?= $item->monto ?></td>
            <td><?= $item->descripcion ?></td>
        </tr>
    </tbody>
<?php endforeach?>
</table>   
<?php require_once './templates/footer.phtml'?>